### ISSUE TITLE
Find some other means of declaring the MSG_ translation variables in the proc's, instead of enumaring every single one of them

### ISSUE THREAD

**Issue by eelcohn** [eelcohn/Telegram-API#2]

**Comment by Pixelz** [comment]
You could use the [msgcat](http://tcl.tk/man/tcl8.6/TclCmd/msgcat.htm) package, which is part of the Tcl core. It is meant to solve this very problem in a convenient way.

**Comment by eelcohn** [comment]
Thanks, I'll look into that

**Comment by nailyk-fr** [comment]
Using an array should also be possible, IIRC you can use string as array index. A bit tricky however.

**Comment by eelcohn** [comment]
Example is at http://forum.egghelp.org/viewtopic.php?p=92697

**Comment by eelcohn** [comment]
Fixed in 3240d40 0c06efb 3dcce4d c004dbf 5355fbc 6d2a918 663c7df 98bebc9
