### ISSUE TITLE
Generic Unicode library for Tcl crash

### ISSUE THREAD

**Issue by avieks** [eelcohn/Telegram-API#56]
It crashes for me as soon as i source /path/to/your/scripts/Telegram-API.tcl and rehash my Eggdrop.

`bad option "decode": must be format or scan`<br/>`
    while executing`<br/>`
"binary decode hex [format %x $byte1][format %x $byte2][format %x $byte3][format %x $byte4]"`<br/>`
    (procedure "::libunicode::escaped2utf8" line 37)`<br/>`
    invoked from within`<br/>`
"::libunicode::escaped2utf8 $escapedstring"`<br/>`
    ("foreach" body line 2)`<br/>`
    invoked from within`<br/>`
"foreach {escapedstring asciistring} [array get ::libunicode::escapedtable] {`<br/>`
	set ::libunicode::utf8table([::libunicode::escaped2utf8 $escapedstring])..."`

Someone else?

**Comment by eelcohn** [comment]
Hi avieks,
Thanks for your feedback. What Tcl version are you using?

**Comment by avieks** [comment]
8.6.5

**Comment by eelcohn** [comment]
I've finally got around to compiling Tcl8.6.5 for testing this scenario, but I cannot reproduce it.
Can you open the tclsh prompt and try some commands for me?
```
% puts [binary decode hex 41424344]
ABCD
% puts [info patchlevel]
8.6.5
% exit
```

**Comment by avieks** [comment]
I get exactly the same output.
Could it be Eggdrop 1.8.3 and/or other loaded scripts?
Either way, I'm going to try with a fresh Eggdrop install locally without other scripts loaded.

**Comment by avieks** [comment]
I've solved this. I had to pass --with-tclinc=<path-to-tcl-inc> and --with-tcllib=<path-to-tcl-lib> to ./configure of Eggdrop.

Thanks for the help anyway, @eelcohn !

**Comment by eelcohn** [comment]
You're welcome! Glad to hear that it's fixed now.
